// @PROJECT_NAME@ - MainWindow implementation
// Generated by project-generator

#include "mainwindow.h"
#include <QMenuBar>
#include <QStatusBar>
#include <QMessageBox>
#include <QPushButton>
#include <QVBoxLayout>
#include <QWidget>

MainWindow::MainWindow(QWidget *parent)
    : QMainWindow(parent) {
    
    // Create central widget
    QWidget *centralWidget = new QWidget(this);
    QVBoxLayout *layout = new QVBoxLayout(centralWidget);
    
    // Add a placeholder label
    QLabel *label = new QLabel("@PROJECT_NAME@ - Qt Application", this);
    label->setAlignment(Qt::AlignCenter);
    layout->addWidget(label);
    
    // Add a button
    QPushButton *btn = new QPushButton("Click Me", this);
    connect(btn, &QPushButton::clicked, this, &MainWindow::onButtonClicked);
    layout->addWidget(btn);
    
    setCentralWidget(centralWidget);
    
    // Create menu bar
    QMenuBar *menuBar = this->menuBar();
    QMenu *fileMenu = menuBar->addMenu("&File");
    
    QAction *exitAction = new QAction("E&xit", this);
    exitAction->setShortcut(QKeySequence::Quit);
    connect(exitAction, &QAction::triggered, this, &QMainWindow::close);
    fileMenu->addAction(exitAction);
    
    QMenu *helpMenu = menuBar->addMenu("&Help");
    QAction *aboutAction = new QAction("&About", this);
    connect(aboutAction, &QAction::triggered, this, &MainWindow::onAbout);
    helpMenu->addAction(aboutAction);
    
    // Status bar
    statusBar()->showMessage("Ready");
}

MainWindow::~MainWindow() {
}

void MainWindow::onButtonClicked() {
    QMessageBox::information(this, "Info", "@PROJECT_NAME@ - Button clicked!");
}

void MainWindow::onAbout() {
    QMessageBox::about(this, "About @PROJECT_NAME@",
        "<h3>@PROJECT_NAME@</h3>"
        "<p>A Qt-based application generated by project-generator.</p>"
        "<p>Version: 1.0.0</p>");
}
