// @PROJECT_NAME@ - Main entry point (Qt 5.15)
// Generated by project-generator

#include <QApplication>
#include <QDebug>
#include <QSysInfo>
#include "mainwindow.h"

int main(int argc, char *argv[]) {
    QApplication app(argc, argv);
    
    qDebug() << "========================================";
    qDebug() << "  @PROJECT_NAME@";
    qDebug() << "  Qt Version:" << qVersion();
    qDebug() << "========================================";
    
    MainWindow w;
    w.setWindowTitle("@PROJECT_NAME@");
    w.resize(800, 600);
    w.show();
    
    return app.exec();
}
