// @PROJECT_NAME@ - MainWindow header
// Generated by project-generator

#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <QMainWindow>

class MainWindow : public QMainWindow {
    Q_OBJECT

public:
    explicit MainWindow(QWidget *parent = nullptr);
    ~MainWindow();

private slots:
    void onButtonClicked();
    void onAbout();

private:
    // Ui::MainWindow *ui;  // If using Qt Designer
};

#endif // MAINWINDOW_H
