// @PROJECT_NAME@ - Common header
// Generated by project-generator

#ifndef COMMON_H
#define COMMON_H

#include <cstdint>
#include <cstdlib>
#include <iostream>
#include <string>

// Version info
#define VERSION_MAJOR 1
#define VERSION_MINOR 0
#define VERSION_PATCH 0

#endif // COMMON_H
